# Generated by Django 5.0.6 on 2024-07-10 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('SH', 'Shopping'), ('WO', 'Work'), ('EN', 'Entertain'), ('FA', 'Family'), ('UN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
