# Generated by Django 5.0.6 on 2024-07-11 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_todo_created_at_todo_deadline_todo_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='type',
            field=models.CharField(choices=[('Shopping', 'Shopping'), ('Work', 'Work'), ('Entertain', 'Entertain'), ('Family', 'Family'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
    ]
